<?php

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class TSAC_Options {
    private $options_options;

    public function __construct() {
        add_action( 'admin_menu', array( $this, 'options_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'options_page_init' ) );
    }

    public function options_add_plugin_page() {
        add_submenu_page(
            'edit.php?post_type=tsa_product', // parent_slug
            __( 'Settings', 'tsa-commerce' ), // page_title
            __( 'Settings', 'tsa-commerce' ), // menu_title
            'manage_options', // capability
            'settings', // menu_slug
            array( $this, 'options_create_admin_page' ) // function
        );
    }

    public function options_create_admin_page() {
        $this->options_options = get_option( 'options_option_name' ); ?>

        <div class="wrap">
            <h2><?php _e( 'Additional configuration', 'tsa-commerce' ) ?></h2>
            <p><?php _e( 'From here you can add your Amazon Associates ID to make it easier to generate urls.', 'tsa-commerce' ) ?></p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                    settings_fields( 'options_option_group' );
                    do_settings_sections( 'options-admin' );
                    submit_button();
                ?>
            </form>
        </div>
    <?php }

    public function options_page_init() {
        register_setting(
            'options_option_group', // option_group
            'options_option_name', // option_name
            array( $this, 'options_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'options_setting_section', // id
            __( 'Settings', 'tsa-commerce' ), // title
            array( $this, 'options_section_info' ), // callback
            'options-admin' // page
        );

        add_settings_field(
            'tsa_amazon_associates_id', // id
            __( 'Amazon Associates ID', 'tsa-commerce' ), // title
            array( $this, 'tsac_amazon_associates_id_callback' ), // callback
            'options-admin', // page
            'options_setting_section' // section
        );

        add_settings_field(
            'tsa_show_price', // id
            __( 'Show price?', 'tsa-commerce' ), // title
            array( $this, 'tsac_show_price_callback' ), // callback
            'options-admin', // page
            'options_setting_section' // section
        );
    }

    public function options_sanitize($input) {
        $sanitary_values = array();
        if ( isset( $input['tsa_amazon_associates_id'] ) ) {
            $sanitary_values['tsa_amazon_associates_id'] = sanitize_text_field( $input['tsa_amazon_associates_id'] );
        }

        if ( isset( $input['tsa_show_price'] ) ) {
            $sanitary_values['tsa_show_price'] = $input['tsa_show_price'];
        }

        return $sanitary_values;
    }

    public function options_section_info() {

    }

    public function tsac_amazon_associates_id_callback() {
        printf(
            '<input class="regular-text" type="text" name="options_option_name[tsa_amazon_associates_id]" id="tsa_amazon_associates_id" value="%s">',
            isset( $this->options_options['tsa_amazon_associates_id'] ) ? esc_attr( $this->options_options['tsa_amazon_associates_id']) : ''
        );
    }

    public function tsac_show_price_callback() {
        ?> <select name="options_option_name[tsa_show_price]" id="tsa_show_price">
            <?php $selected = (isset( $this->options_options['tsa_show_price'] ) && $this->options_options['tsa_show_price'] === '1') ? 'selected' : '' ; ?>
            <option value="1" <?php echo $selected; ?>><?php _e( 'Only in products with price', 'tsa-commerce' ) ?></option>
            <?php $selected = (isset( $this->options_options['tsa_show_price'] ) && $this->options_options['tsa_show_price'] === '0') ? 'selected' : '' ; ?>
            <option value="0" <?php echo $selected; ?>><?php _e( 'No', 'tsa-commerce' ) ?></option>
        </select> <?php
    }

}
if ( is_admin() )
    $options = new TSAC_Options();

/*
 * Retrieve this value with:
 * $options_options = get_option( 'options_option_name' ); // Array of All Options
 * $tsa_amazon_associates_id = $options_options['tsa_amazon_associates_id']; // Amazon Associates ID
 * $tsa_show_price = $options_options['tsa_show_price']; // Show price?
 */
